# veco_server.py
# -----------------------------------------------------------------------------
# veco-ai REST API server — wraps the Vectorize class with a FastAPI interface.
#
# Start:
#   python -m veco_ai.veco_server
#   uvicorn veco_ai.veco_server:app --host 0.0.0.0 --port 8000 --reload
#
# Interactive docs (auto-generated by FastAPI):
#   http://localhost:8000/docs
#
# Configuration via environment variables:
#   VECO_EMBEDDING_MODEL   sentence-transformers model (default: BAAI/bge-m3)
#   VECO_EMBEDDER_BACKEND  "sbert" | "ollama"  (default: sbert)
#   VECO_OLLAMA_EMBED      Ollama embed model  (default: nomic-embed-text)
#   VECO_VISION_MODEL      Ollama vision model (default: gemma4)
#   VECO_LLM_MODEL         Ollama LLM for RAG  (default: gemma3:12b)
#   VECO_INDEX_TYPE        "flat" | "hnsw"     (default: flat)
#   VECO_USE_CLIP          "true" | "false"    (default: false)
#   VECO_DB_PATH           JSON database path  (default: vector_db.json)
#   VECO_LANGUAGE          ASR language code   (default: de)
#   VECO_HOST              server host         (default: 0.0.0.0)
#   VECO_PORT              server port         (default: 8000)
# -----------------------------------------------------------------------------

from __future__ import annotations
import os
import tempfile
import threading
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np

try:
    from fastapi import FastAPI, File, HTTPException, UploadFile, BackgroundTasks
    from fastapi.responses import RedirectResponse
    from pydantic import BaseModel, Field
    import uvicorn
    _FASTAPI_OK = True
except ImportError:
    raise RuntimeError(
        "FastAPI and uvicorn are required for veco_server. Install:\n"
        "  pip install fastapi uvicorn[standard] python-multipart"
    )

from .veco_ai import Vectorize

# ---------------------------------------------------------------------------
# Config from environment
# ---------------------------------------------------------------------------

_CFG = {
    "embedding_model": os.getenv("VECO_EMBEDDING_MODEL", "BAAI/bge-m3"),
    "embedder_backend": os.getenv("VECO_EMBEDDER_BACKEND", "sbert"),
    "ollama_embed_model": os.getenv("VECO_OLLAMA_EMBED", "nomic-embed-text"),
    "vision_model": os.getenv("VECO_VISION_MODEL", "gemma4"),
    "default_model": os.getenv("VECO_LLM_MODEL", "gemma3:12b"),
    "index_type": os.getenv("VECO_INDEX_TYPE", "flat"),
    "use_clip": os.getenv("VECO_USE_CLIP", "false").lower() == "true",
    "db_path": os.getenv("VECO_DB_PATH", "vector_db.json"),
    "language": os.getenv("VECO_LANGUAGE", "de"),
}

# ---------------------------------------------------------------------------
# Global state
# ---------------------------------------------------------------------------

_veco: Optional[Vectorize] = None
_write_lock = threading.Lock()  # serializes FAISS writes (reads are concurrent-safe)


def _get_veco() -> Vectorize:
    if _veco is None:
        raise HTTPException(status_code=503, detail="Vectorize engine not initialized")
    return _veco


# ---------------------------------------------------------------------------
# Lifespan: init + shutdown
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    global _veco
    _veco = Vectorize(
        default_model=_CFG["default_model"],
        vision_model=_CFG["vision_model"],
        embedding_model=_CFG["embedding_model"],
        embedder_backend=_CFG["embedder_backend"],
        ollama_embed_model=_CFG["ollama_embed_model"],
        preload_json_path=_CFG["db_path"],
        language=_CFG["language"],
        index_type=_CFG["index_type"],
        use_clip=_CFG["use_clip"],
    )
    yield
    if _veco is not None:
        _veco.close()


# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = FastAPI(
    title="veco-ai API",
    description=(
        "Multimodal RAG API — ingest documents, audio, video, images, and CAD files "
        "into a FAISS vector database and answer questions via a local Ollama LLM."
    ),
    version="0.2.0",
    lifespan=lifespan,
)


# ---------------------------------------------------------------------------
# Pydantic request / response models
# ---------------------------------------------------------------------------

class IngestPathRequest(BaseModel):
    path: str = Field(..., description="Absolute or relative path to the file to ingest")
    use_compression: bool = Field(False, description="Generate and store an LLM summary")
    use_diarization: Optional[bool] = Field(
        None, description="Speaker diarization (None = auto-detect for audio/video)"
    )
    save_db: bool = Field(True, description="Persist the database after ingestion")


class QueryRequest(BaseModel):
    question: str
    database: str = Field(_CFG["db_path"], description="Database path or URI to query")
    llm_model: str = Field(_CFG["default_model"], description="Ollama model for the answer")
    top_k: int = Field(5, ge=1, le=50)
    include_summary: bool = True


class SearchRequest(BaseModel):
    query: str = Field(..., description="Natural language search query")
    top_k: int = Field(5, ge=1, le=50)


class ClipTextSearchRequest(BaseModel):
    text: str = Field(..., description="Text query for cross-modal image retrieval via CLIP")
    top_k: int = Field(5, ge=1, le=50)


class EmbedRequest(BaseModel):
    texts: List[str] = Field(..., description="Texts to embed")


class SwitchDatabaseRequest(BaseModel):
    database: str = Field(..., description="JSON path, SQLite path, or MongoDB URI")


class StatusResponse(BaseModel):
    status: str
    vector_count: int
    clip_vector_count: int
    embedding_model: str
    embedder_backend: str
    index_type: str
    use_cosine: bool
    use_clip: bool
    active_db: str
    audio_available: bool


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/", include_in_schema=False)
async def root():
    return RedirectResponse(url="/docs")


@app.get("/status", response_model=StatusResponse, tags=["system"])
async def status():
    """Health check and engine statistics."""
    veco = _get_veco()
    return {
        "status": "ok",
        "vector_count": veco.faiss_index.ntotal,
        "clip_vector_count": veco._clip_index.ntotal if veco._use_clip else 0,
        "embedding_model": type(veco.embedder).__name__,
        "embedder_backend": (
            "ollama" if type(veco.embedder).__name__ == "OllamaEmbedder" else "sbert"
        ),
        "index_type": veco._index_type,
        "use_cosine": veco._use_cosine,
        "use_clip": veco._use_clip,
        "active_db": veco._active_db or veco.preload_json_path,
        "audio_available": veco.audio_available,
    }


@app.post("/ingest/path", tags=["ingest"])
async def ingest_path(req: IngestPathRequest, background_tasks: BackgroundTasks):
    """
    Vectorize a file by local path.
    The task runs in the background; returns immediately with status 'queued'.
    Poll /status to see the updated vector_count when done.
    """
    veco = _get_veco()
    if not Path(req.path).exists():
        raise HTTPException(status_code=404, detail=f"File not found: {req.path}")

    def _run() -> None:
        with _write_lock:
            veco.vectorize(
                req.path,
                use_compression=req.use_compression,
                use_diarization=req.use_diarization,
            )
            if req.save_db:
                veco.save_database()

    background_tasks.add_task(_run)
    return {"status": "queued", "path": req.path}


@app.post("/ingest/file", tags=["ingest"])
async def ingest_file(
    file: UploadFile = File(...),
    use_compression: bool = False,
):
    """
    Upload a file and vectorize it synchronously.
    Supports any file type handled by veco (PDF, DOCX, MP3, MP4, JPG, STL, …).
    """
    veco = _get_veco()
    suffix = Path(file.filename or "upload").suffix or ".bin"
    with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as tmp:
        tmp.write(await file.read())
        tmp_path = tmp.name
    try:
        with _write_lock:
            veco.vectorize(tmp_path, use_compression=use_compression)
            veco.save_database()
        return {
            "status": "ingested",
            "filename": file.filename,
            "vector_count": veco.faiss_index.ntotal,
        }
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass


@app.post("/query", tags=["rag"])
async def query(req: QueryRequest):
    """
    End-to-end RAG: retrieve context from the vector database, then generate
    an answer via the configured Ollama LLM.
    """
    veco = _get_veco()
    try:
        return veco.query(
            database=req.database,
            question=req.question,
            llm_model=req.llm_model,
            top_k=req.top_k,
            include_summary=req.include_summary,
        )
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail=str(exc))


@app.post("/search", tags=["retrieval"])
async def search(req: SearchRequest):
    """
    Semantic similarity search — returns the top-k matching text chunks
    without calling an LLM.
    """
    veco = _get_veco()
    results = veco.retrieve_context(req.query, top_k=req.top_k)
    return {"query": req.query, "results": results}


@app.get("/search", tags=["retrieval"])
async def search_get(q: str, top_k: int = 5):
    """Quick semantic search via GET (browser-friendly)."""
    veco = _get_veco()
    results = veco.retrieve_context(q, top_k=top_k)
    return {"query": q, "results": results}


@app.post("/search/clip", tags=["retrieval"])
async def search_clip_text(req: ClipTextSearchRequest):
    """
    Cross-modal retrieval: find images that match a text description via CLIP.
    Requires the server to be started with VECO_USE_CLIP=true.
    """
    veco = _get_veco()
    if not veco._use_clip:
        raise HTTPException(
            status_code=400,
            detail="CLIP is not enabled. Restart the server with VECO_USE_CLIP=true.",
        )
    results = veco.search_by_text_clip(req.text, top_k=req.top_k)
    return {"text": req.text, "results": results}


@app.post("/search/clip/image", tags=["retrieval"])
async def search_clip_image(file: UploadFile = File(...), top_k: int = 5):
    """
    Find images similar to the uploaded image using CLIP (image→image search).
    Requires VECO_USE_CLIP=true.
    """
    veco = _get_veco()
    if not veco._use_clip:
        raise HTTPException(
            status_code=400,
            detail="CLIP is not enabled. Restart the server with VECO_USE_CLIP=true.",
        )
    suffix = Path(file.filename or "img").suffix or ".jpg"
    with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as tmp:
        tmp.write(await file.read())
        tmp_path = tmp.name
    try:
        results = veco.search_by_image(tmp_path, top_k=top_k)
        return {"filename": file.filename, "results": results}
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass


@app.post("/embed", tags=["embeddings"])
async def embed(req: EmbedRequest):
    """
    Return raw embeddings for a list of texts.
    Useful for integrating veco embeddings into external pipelines
    (e.g. n8n, LangChain, custom rerankers).
    """
    veco = _get_veco()
    vecs = veco.embed_texts(req.texts)
    return {
        "embeddings": vecs.tolist(),
        "model": type(veco.embedder).__name__,
        "dim": int(vecs.shape[1]) if vecs.ndim > 1 else 0,
        "count": len(req.texts),
    }


@app.post("/database/switch", tags=["database"])
async def switch_database(req: SwitchDatabaseRequest):
    """Switch the active vector database (JSON, SQLite, or MongoDB)."""
    veco = _get_veco()
    with _write_lock:
        veco._switch_database(req.database)
    return {"status": "switched", "database": req.database}


@app.delete("/database", tags=["database"])
async def clear_database():
    """Clear all records from the active database (irreversible)."""
    veco = _get_veco()
    with _write_lock:
        veco._reset_in_memory_state()
        veco.save_database()
    return {"status": "cleared", "vector_count": 0}


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    uvicorn.run(
        "veco_ai.veco_server:app",
        host=os.getenv("VECO_HOST", "0.0.0.0"),
        port=int(os.getenv("VECO_PORT", "8000")),
        reload=os.getenv("VECO_RELOAD", "false").lower() == "true",
    )


if __name__ == "__main__":
    main()
